- hosts: web
  tasks:
  - name: "copy website"
    copy:
      src: site/
      dest: /var/www/default
- hosts: host01
  tasks:
  - name: "change html in 8081"
    replace: 
        path: /var/www/default/index.html
        regexp: 'Thanaporn'
        replace: 'eieiei'
        backup: yes
- hosts: host02
  tasks:
  - name: "change html in 8082"
    replace: 
        path: /var/www/default/index.html
        regexp: 'Thanaporn'
        replace: '8082 Thanaporn'
        backup: yes
        
- hosts: host03
  tasks:
  - name: "change html in 8082"
    replace: 
        path: /var/www/default/index.html
        regexp: 'Panggam'
        replace: 'Panngam 8083'
        backup: yes
